server:
  port: 5000

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/~~~~~
    username: postgres
    password: ~~~~~
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      pool-name: HikariPool-SpringBootKotlinVirtualThread
      minimum-idle: 10
      maximum-pool-size: 50
      max-lifetime: 1800000
      idle-timeout: 1500000
  jpa:
    open-in-view: false
#    properties:
#      hibernate.transaction.jta.platform: org.hibernate.service.jta.JtaPlatform
  redis:
    redisson:
      config:
        singleServerConfig:
          address: redis://localhost:6379
          password: ~~~~~
          database: 0
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          subscriptionsPerConnection: 5
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 24
          connectionPoolSize: 64
          dnsMonitoringInterval: 5000
        threads: 0
        nettyThreads: 0
        transportMode: "NIO"

# JWT 설정
jwt:
  secret-key: "~~~~~"
  access-token-validity-in-seconds: 86400  # 24시간
  refresh-token-validity-in-seconds: 604800  # 7일

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE